proxies:
- name: miku
  type: vmess
  server: quiz.vidio.com
  port: 443
  uuid: d8067f2a-7f2c-49d1-8483-1ba3daa42321
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: idv5.wibuserver.cloud
  network: ws
  udp: true
  ws-opts:
    path: /vmess
    headers:
      Host: idv5.wibuserver.cloud
- name: miku[1]
  type: vmess
  server: quiz.vidio.com
  port: 80
  uuid: d8067f2a-7f2c-49d1-8483-1ba3daa42321
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: idv5.wibuserver.cloud
  network: ws
  udp: true
  ws-opts:
    path: /vmess
    headers:
      Host: idv5.wibuserver.cloud
- name: miku[2]
  type: vmess
  server: quiz.vidio.com
  port: 443
  uuid: d8067f2a-7f2c-49d1-8483-1ba3daa42321
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: idv5.wibuserver.cloud
  network: grpc
  udp: true
  grpc-opts:
    grpc-service-name: vmess
- name: miku[3]
  type: vmess
  server: quiz.vidio.com
  port: 443
  uuid: d8067f2a-7f2c-49d1-8483-1ba3daa42321
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: idv5.wibuserver.cloud
  network: ws
  udp: true
  ws-opts:
    path: /upvmess
    headers:
      Host: idv5.wibuserver.cloud
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true
- name: miku[4]
  type: vmess
  server: quiz.vidio.com
  port: 80
  uuid: d8067f2a-7f2c-49d1-8483-1ba3daa42321
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: idv5.wibuserver.cloud
  network: ws
  udp: true
  ws-opts:
    path: /upvmess
    headers:
      Host: idv5.wibuserver.cloud
    v2ray-http-upgrade: true
    v2ray-http-upgrade-fast-open: true